### ISSUE TITLE
Content entry

### ISSUE THREAD

**Issue by KevinJordil** [gen-classroom/projet-diserens_jordil_sciarra#16]
As a user, I would like to be able to enter content in a simplified markup format such as Markdown
or Asciidoctor to be compiled into HTML.

**Comment by DS-Daniel** [comment]
Research information about differences between Markdowm and Asciidoctor and converting them into HTML format.

Estimated time of completion :
- optimistic : 30
- pessimistic : 1h30
- expected : 40-50

**Comment by DS-Daniel** [comment]
After researching, Markdown was chosen and a plugin to convert md files to html was found.
Time spent : 1h

**Comment by DS-Daniel** [comment]
Adding plugin to project and implementation of the feature (command to convert md file from a source to a html file)

Estimated time of completion :
- optimistic : 1h
- pessimistic : 3h
- expected : 1h40

**Comment by DS-Daniel** [comment]
> 
> 
> Adding plugin to project and implementation of the feature (command to convert md file from a source to a html file)
> 
> Estimated time of completion :
> 
>     * optimistic : 1h
> 
>     * pessimistic : 3h
> 
>     * expected : 1h40

Moved to issue 20
