### ISSUE TITLE
Initialise a static site

### ISSUE THREAD

**Issue by KevinJordil** [gen-classroom/projet-diserens_jordil_sciarra#19]
As a user, I would like to run the following command to initialise a static site.
```
$ statique init /mon/site
```
In other words, the init subcommand could create or populate the folder named /my/site with a
config.yaml file containing general information about the site (title, description, domain, etc.) and
a Markdown file index.md containing a home page with metadata and content.

**Comment by LoisDiserens** [comment]
Estimated time of completion :

    Learning to use Picocli: 30min
    Implementing the feature: 20 min
    expected in total: 50 min

**Comment by LoisDiserens** [comment]
Ce qui causait problème: les différents main (des exemples de picocli) qui empiétaient sur le main de Statique.Java

Marche à suivre pour résoudre:

1. Effacer Main.Java, App.Java et AppTest
2. Depuis le repot : https://github.com/gen-classroom/statique 
    il faut recopier le pom.xml et assembly/assembly.xml dans ceux de notre projet
3. Faire un mvn clean install
4. Dans le dossier target, dé-zipper à la racine du projet le fichier statique.zip
5. Effectuer la marche à suivre sur https://github.com/gen-classroom/statique 
ATTENTION SUR WINDOWS, LA COMMANDE RM TELLE QU ELLE VA SUPPRIMER DES FICHIERS DEPUIS LA RACINE DU DISQUE (expérience faite ;( )

**Comment by LoisDiserens** [comment]
Temps effectif pris pour faire cette tâche : environ 3 jours
Ce surplus de temps considérable est du à 2 problèmes non-attendus qui sont survenus.

Problèmes rencontrés:
1.  Suite à une commande faite pour Unix, lancée sous Windows 10, une partie de mon disque c'est supprimer à la racine, des données ainsi que certains fichier de l'OS ont étés atteint. Ne sachant pas à quel point le système était touché, j'ai été contraint à devoir réinstaller mon système. Sauvegarder mes données restantes, réinstaller le système, ainsi que chaque logiciels et configurations requises pour chacun des cours suivis, cela m'a pris environ une soirée + une matinée.

2. commande statique introuvable sous Windows via le cmd, j'ai du remonter le problème à l'assistant, James, ainsi qu'au prof, qui ont du développer un équivalent de leur script de création de commande bash (Unix) pour Windows. Ils ont créés un bat qui fait le travail pour Windows, cependant, il faut executer la commande "statique" via une console PowerShell et non pas le cmd basique (Il faut aussi s'assurer d'avoir la variable d'environnement PATH qui pointe bien vers le dossier (statique/bin) provenant du zip créé dans "target" une fois la commande "mvn clean install" executée).
