### ISSUE TITLE
Compile a static site

### ISSUE THREAD

**Issue by KevinJordil** [gen-classroom/projet-diserens_jordil_sciarra#20]
As a user, I would like to run the following command in order to compile the static site.
```
$ statique build /mon/site
```
In other words, the build subcommand creates a /my/site/build folder containing an HTML
file corresponding to the content of each page of the static site (the metadata can be ignored for the moment).
Some files such as configuration files should not be added to the build folder. Example:
| /mon/site/                                                                                | /mon/site/build/                                                            |
|-------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------|
| - dossier/<br>       ---- page.md<br>       ---- image.png<br> - index.md<br> - config.yaml<br> | - dossier/<br>       ---- page.html<br>       ---- image.png<br> - index.html<br> |

**Comment by DS-Daniel** [comment]
Estimated time of completion :
    optimistic : 20min
    pessimistic : 1h
    expected : 35min
