### ISSUE TITLE
Cleaning up a static site

### ISSUE THREAD

**Issue by KevinJordil** [gen-classroom/projet-diserens_jordil_sciarra#21]
As a user, I would like to run the static clean /my/site command in order to clean the
static site. In other words, the clean subcommand should delete the /my/site/build folder.

**Comment by LoisDiserens** [comment]
Delete le contenu d'un dossier de manière récursive : https://stackoverflow.com/questions/20281835/how-to-delete-a-folder-with-files-using-java
Méthode des FileUtils.deleteDirectory

**Comment by LoisDiserens** [comment]
Expected Timing:
Research: 20 min
Coding: 20 min

**Comment by LoisDiserens** [comment]
Effective Timing:
Research: 10 min
Coding: 10 min
