### ISSUE TITLE
Create Tests for each tasks in sprint 2

### ISSUE THREAD

**Issue by LoisDiserens** [gen-classroom/projet-diserens_jordil_sciarra#43]
Creates tests for each tasks in sprint 2 (see the docx file for specifications / issues created in this Kanban)

**Comment by DS-Daniel** [comment]
Test for TemplateEngine and for Build command
Estimated time:
-optimistic : 30min
-pessimistic : 1h30
-expected : 1h

**Comment by DS-Daniel** [comment]
Time spent : 1h30
Some problems of understanding with the java io/nio library. 
Incomprehensible problem with a junit exception, so no debugging possible with intellij when setting up tests.
Incomprehensible problem with identical files not considered as identical with FileUtils.contentEquals.
