### ISSUE TITLE
On-the-go static site generation

### ISSUE THREAD

**Issue by DS-Daniel** [gen-classroom/projet-diserens_jordil_sciarra#57]

**Comment by DS-Daniel** [comment]
En tant qu’utilisateur, j’aimerai que les commandes build et serve puissent régénérer le site statique à la volée, c’est-
à-dire de manière automatique lorsque des changements sont effectués sur le système de fichier. Pour cela, ajoutez
une option --watch aux commandes build et serve et assurez-vous que leur exécution ne se termine pas à la fin du
premier build.
Les générateurs de site statique Jekyll1 et Hugo2 disposent tous deux d’une option --watch. La WatchService API3 de
la librairie standard Java permet d’écouter les changements effectués sur le système de fichiers.
Question ouverte : Faut-il recompiler tous les fichiers lors de chaque changement ?

**Comment by LoisDiserens** [comment]
Temps estimé : 4H (1H recherches + 1H implémentation + 2H tests et résolution de bug)

**Comment by LoisDiserens** [comment]
Réponse à la question ouverte: Alors oui ca serait le plus optimal de rebuild juste le fichier modifier dans la structure, car par exemple si nous avons une grande infra, cela pourrait prendre beaucoup de temps de tout recompiler. Néanmoins, nous n'avons pas le temps de nous atteler a refaire complétement notre fichier Build pour parvenir a cette implémentation là (nous allons donc rebuild tous le dossier à chaque fois).

**Comment by DS-Daniel** [comment]
reviewed
