### ISSUE TITLE
Javadoc

### ISSUE THREAD

**Issue by DS-Daniel** [gen-classroom/projet-diserens_jordil_sciarra#59]
Configurer Maven de manière à pouvoir publier une javadoc au format HTML4. Ajouter la Javadoc à votre release.

**Comment by KevinJordil** [comment]
Temps estimé: 2h
Time passé: 1h30

La partie qui m'a pris le plus de temps était de générer la javadoc avant de créer un zip.
Le reste était une copie puis adaptation de la partie qui générait le zip "statique"
