### ISSUE TITLE
Code benchmarking

### ISSUE THREAD

**Issue by DS-Daniel** [gen-classroom/projet-diserens_jordil_sciarra#62]
Utiliser JMH8 pour mesurer les performances de votre compilateur markdown ou de votre moteur de rendu. Utiliser VisualVM9 pour profiler une exécution de la commande build. Incluez ces données dans votre rapport et discuter d’une éventuelle optimisation (sans nécessairement l’implémenter).

**Comment by LoisDiserens** [comment]
Temps estimé : Visionnage VOD explication du prof (1H) + implémentation (30') + debug et tests (1H) = 2H30'

**Comment by LoisDiserens** [comment]
Temps effectif: 2H (temps de debug moins long que prévu)
